#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Vijay Zhou's site

# Short bio or description (displayed in the header)
description: A Web Developer from Somewhere

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://7xib2u.com1.z0.glb.clouddn.com/avatar.jpg

imghost: http://7xib2u.com1.z0.glb.clouddn.com

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  github: jzlingmo/
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: http://jzlingmo.github.io



###### JEKYLL CONFIG
version: v2.4.0 # version of Jekyll

### DEFAULT USER CONFIGURATION

permalink: blog/:categories/:year/:month/:day/:title/ # pretty /:categories/:year/:month/:day/:title/ # default to date
paginate: 10 # max items per page
paginate_path: /blog/page:num # default to /page:num

sass:
  # sass_dir: _sass # the Sass partials directory, as we're using @imports
  style: :compressed # :compressed or :expanded

defaults:
  # all site
  -
    scope:
      path: "" # an empty string here means all files in the project
      layout: "default"

    values: # values will be scoped to any file that in the scopes path
      author: "jzlingmo"
  # only posts
  -
    scope:
      type: "posts" # pages, posts, drafts

    values:
      layout: "post"
      author: "jzlingmo"


### GLOBAL CONFIGURATION
# Refer http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
exclude:
    - Gemfilew
    - Gemfile.lock
    - LICENSE
    - README.md

### BUILD COMMAND OPTION
# future: true # Publish posts with a future date
lsi: true # Produce an index for related posts.
# limit_posts: 0
# excerpt_separator: "\n\n"
markdown: redcarpet # default to kramdown
highlighter: pygments # default to rouge

### SERVE COMMAND OPTIONS
# host: 127.0.1
# port: 4000
# detach: false
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

### PLUGINS
whitelist: []
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem